services:
  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog
    restart: always
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - backend

  database:
    image: postgres:alpine3.20
    container_name: books-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=booksDBadmin
      - POSTGRES_PASSWORD=coolAdminPass
      - POSTGRES_DB=booksDB
    volumes:
      - books-db-data:/data/db
    depends_on:
      - mailhog
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U booksDBadmin -d booksDB"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  backend:
    container_name: books-backend
    restart: always
    build: 
      context: ./backend
      dockerfile: dockerfile
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000

    depends_on:
      database:
        condition: service_healthy
    networks:
      - backend

volumes:
  books-db-data:

networks:
  backend: