services:
  database:
    image: postgres:alpine3.20
    container_name: books-db
    restart: always
    ports:
      - 5432:5432
    # env_file:
    #   - .env
    environment:
      - POSTGRES_USER=booksDBadmin
      - POSTGRES_PASSWORD=coolAdminPass
      - POSTGRES_DB=booksDB
    volumes:
      - books-db-data:/data/db
    # networks:
    #   - backend


volumes:
  books-db-data:

    # networks:
    #   backend:
    # frontend:
