FROM node:22.5.1-alpine3.20
WORKDIR /backend/

# ARG DB_URL
# ARG SECRET

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 8000

# ENV DATABASE_URL=${DB_URL}
# ENV JWT_SECRET=${SECRET}

RUN npx prisma generate

COPY ./entrypoint.sh /backend/entrypoint.sh

ENTRYPOINT [ "/backend/entrypoint.sh"]