FROM node:22.5.1-alpine3.20
WORKDIR /backend/

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 8000

RUN npx prisma generate

RUN sed -i 's/\r$//' ./entrypoint.sh  && \  
    chmod +x ./entrypoint.sh

CMD ["./entrypoint.sh"]
